import { ToolRegistry } from '@/lib/agents/core/registry';

describe.skip('ToolRegistry', () => {
  test('registerAutoGeneratedGraphQLTools returns tools from mock introspection', async () => {
    const registry = new ToolRegistry();

    const originalFetch = globalThis.fetch;
    globalThis.fetch = async (_input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
      return new Response(
        JSON.stringify({
          data: {
            __schema: {
              types: [
                {
                  kind: 'OBJECT',
                  name: 'Mutation',
                  fields: [
                    {
                      name: 'checkoutCreate',
                      description: 'Create checkout',
                      type: { kind: 'OBJECT', name: 'Checkout', ofType: undefined },
                      args: [
                        {
                          name: 'input',
                          description: 'Checkout input',
                          type: { kind: 'INPUT_OBJECT', name: 'CheckoutCreateInput', ofType: undefined },
                          defaultValue: null,
                        },
                      ],
                    },
                  ],
                },
                {
                  kind: 'INPUT_OBJECT',
                  name: 'CheckoutCreateInput',
                  inputFields: [
                    { name: 'email', description: 'Email', type: { kind: 'SCALAR', name: 'String', ofType: undefined }, defaultValue: null, isRequired: false, isList: false },
                  ],
                },
                {
                  kind: 'OBJECT',
                  name: 'Checkout',
                  fields: [],
                },
                {
                  kind: 'SCALAR',
                  name: 'String',
                },
              ],
            },
          },
        }),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      );
    };

    try {
      await registry.registerAutoGeneratedGraphQLTools({
        endpoint: 'https://example.com/graphql',
        authHeaderName: 'X-Shopify-Storefront-Access-Token',
        authHeaderValue: 'test-token',
      });

      const tool = registry.getTool('gql_mutation_checkoutCreate');
      expect(tool).toBeDefined();
      expect(tool?.name).toBe('gql_mutation_checkoutCreate');
      expect(tool?.risk).toBe('mutative');
      expect(tool?.requiresApproval).toBe(true);
      expect(tool?.schema).toBeDefined();
    } finally {
      globalThis.fetch = originalFetch;
    }
  });
});
