/**
 * World Model — Benchmarking Type Definitions
 * Tech Genie / UCOL Architecture
 *
 * Defines the type system for the Model Self-Benchmarking Feedback Loop.
 * Covers scoring dimensions, benchmark results, performance profiles,
 * routing training examples, and feedback cycle summaries.
 *
 * See: research/world-model/ML_ARCHITECTURE.md
 */

import type { AIOutputAudit } from '../types'

// ─────────────────────────────────────────────
// Scoring Dimensions
// ─────────────────────────────────────────────

/**
 * The 4 orthogonal scoring dimensions used to evaluate an AI model response.
 * All values are normalized to [0.0, 1.0].
 */
export interface BenchmarkDimensions {
  /** Based on claim verdicts from Delta Engine. 1.0 = perfectly accurate. */
  accuracy_score: number
  /** Proportion of CONFIRMED + SUPPORTED claims. 1.0 = all claims verified. */
  claim_quality_score: number
  /** Did the model leverage graph knowledge vs hallucinate? 1.0 = full graph use. */
  graph_utilization_score: number
  /** Normalized response latency against the p95 baseline for this model. */
  latency_score: number
}

// ─────────────────────────────────────────────
// Benchmark Result
// ─────────────────────────────────────────────

/**
 * Multi-objective composite benchmark result for a single AI model response.
 *
 * Composite score formula:
 *   (0.4 × accuracy) + (0.3 × claim_quality) + (0.2 × graph_utilization) + (0.1 × latency)
 */
export interface BenchmarkResult {
  /** Unique identifier (UUID generated by Supabase) */
  id: string
  /** Timestamp this result was created */
  created_at: Date
  /** Session ID linking this result to its conversation */
  session_id: string
  /** AI model that produced the evaluated response */
  model: string
  /** Domain classification for this response */
  domain: string
  /** Individual scoring dimensions */
  dimensions: BenchmarkDimensions
  /** Weighted composite score in [0.0, 1.0] */
  composite_score: number
  /** Actual response latency in milliseconds */
  latency_ms: number
  /** Full claim audit from the Delta Engine */
  audit: AIOutputAudit
  /** ID of the RoutingDecision that selected this model, if available */
  routing_decision_id?: string
}

// ─────────────────────────────────────────────
// Model Performance Profile
// ─────────────────────────────────────────────

/**
 * Aggregated performance profile for a model × domain pair,
 * computed over a rolling 30-day window.
 *
 * Used by the FeedbackLoop to determine routing weights and demotion status.
 */
export interface ModelPerformanceProfile {
  /** AI model identifier */
  model: string
  /** Domain this profile covers */
  domain: string
  /** Start of the 30-day rolling window */
  window_start: Date
  /** End of the 30-day rolling window (typically now) */
  window_end: Date
  /** Total number of benchmark results in this window */
  total_benchmarks: number
  /** Mean composite score across all benchmarks */
  avg_composite_score: number
  /** Mean accuracy dimension score */
  avg_accuracy_score: number
  /** Mean claim quality dimension score */
  avg_claim_quality_score: number
  /** Mean graph utilization dimension score */
  avg_graph_utilization_score: number
  /** Mean response latency in milliseconds */
  avg_latency_ms: number
  /** 95th percentile latency in milliseconds */
  p95_latency_ms: number
  /**
   * Proportion of CONTRADICTED + MISATTRIBUTED claims across the window.
   * Value in [0.0, 1.0] where higher = more hallucination.
   */
  hallucination_rate: number
  /**
   * Performance trend based on last-7d vs last-30d composite score comparison.
   * 'improving' if 7d > 30d × 1.05, 'degrading' if 7d < 30d × 0.95.
   */
  confidence_trend: 'improving' | 'stable' | 'degrading'
  /** Routing weight multiplier for this model in this domain [0.0, 2.0] */
  routing_weight: number
  /** Whether this model is currently suspended from routing for this domain */
  demoted: boolean
  /** Human-readable explanation for demotion, if applicable */
  demotion_reason?: string
}

// ─────────────────────────────────────────────
// Routing Training Example
// ─────────────────────────────────────────────

/**
 * A routing training example written back to ModelStore after each benchmark cycle.
 * Follows the same 10-feature format as RoutingModel's RoutingFeatures.
 */
export interface RoutingTrainingExample {
  /** 10-element feature array matching RoutingModel's feature order */
  features: number[]
  /** The model label that was chosen by routing */
  label: string
  /** Composite benchmark score — the "reward" signal for this routing decision */
  outcome_score: number
  /** Domain this example belongs to */
  domain: string
  /** When this training example was created */
  timestamp: Date
}

// ─────────────────────────────────────────────
// Feedback Loop Cycle Summary
// ─────────────────────────────────────────────

/**
 * Summary of all actions taken during one FeedbackLoop.runCycle() execution.
 */
export interface FeedbackLoopCycle {
  /** When this cycle ran */
  ran_at: Date
  /** Total number of unprocessed benchmarks consumed */
  benchmarks_processed: number
  /** Number of model × domain profiles that were updated */
  profiles_updated: number
  /** Number of routing training examples written to ModelStore */
  training_examples_written: number
  /** Models (model:domain strings) that were demoted this cycle */
  models_demoted: string[]
  /** Models (model:domain strings) that were reinstated this cycle */
  models_reinstated: string[]
  /** Number of routing weight records upserted */
  routing_weights_adjusted: number
}
