import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import axios from "axios";
import { VertexAI } from "@google-cloud/vertexai";

const SLACK_API_BASE = "https://slack.com/api";

// Initialize Vertex AI
const vertexAI = new VertexAI({ project: process.env.GCLOUD_PROJECT || "ai-nexus-saas", location: "us-central1" });
const model = vertexAI.getGenerativeModel({ model: "gemini-1.5-flash-001" });

/**
 * Scheduled Function: Send Daily Summaries
 * Runs every day at 9:00 AM
 */
export const sendDailySummaries = functions.pubsub.schedule("every 24 hours").onRun(async (context) => {
  const db = admin.firestore();
  console.log("[DAILY_SUMMARY] Starting daily summary generation...");

  try {
    // 1. Find users with enabled Slack notifications
    // Use collection group query on 'profile' documents
    const profilesSnapshot = await db.collectionGroup("profile")
      .where("integrations.slackEnabled", "==", true)
      .where("integrations.slackTeamId", ">=", "") // Ensure teamId exists
      .get();

    console.log(`[DAILY_SUMMARY] Found ${profilesSnapshot.size} profiles with Slack enabled`);

    const processedChannels = new Set<string>();

    for (const doc of profilesSnapshot.docs) {
      const data = doc.data();
      const integration = data.integrations;
      const { slackChannelId, slackTeamId } = integration;

      // Avoid duplicate summaries for same channel (if multiple users configured same channel)
      const channelKey = `${slackTeamId}:${slackChannelId}`;
      if (processedChannels.has(channelKey)) {
        continue;
      }
      processedChannels.add(channelKey);

      try {
        await generateAndSendSummary(slackTeamId, slackChannelId);
      } catch (err) {
        console.error(`[DAILY_SUMMARY] Failed for channel ${slackChannelId}:`, err);
      }
    }
  } catch (error) {
    console.error("[DAILY_SUMMARY] Fatal error:", error);
  }
});

async function generateAndSendSummary(teamId: string, channelId: string) {
  const db = admin.firestore();

  // 2. Get Bot Token
  const installationDoc = await db.collection("slack_installations").doc(teamId).get();
  if (!installationDoc.exists) {
    console.warn(`[DAILY_SUMMARY] No installation found for team ${teamId}`);
    return;
  }

  const installation = installationDoc.data();
  const token = installation?.bot?.token;

  if (!token) {
    console.warn(`[DAILY_SUMMARY] No bot token for team ${teamId}`);
    return;
  }

  // 3. Fetch recent history (Last 24h)
  const yesterday = (Date.now() / 1000) - (24 * 60 * 60);

  const historyResponse = await axios.post(`${SLACK_API_BASE}/conversations.history`, {
    channel: channelId,
    oldest: yesterday,
    limit: 100
  }, {
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json"
    }
  });

  if (!historyResponse.data.ok) {
    throw new Error(`Slack API error: ${historyResponse.data.error}`);
  }

  const messages = historyResponse.data.messages || [];
  if (messages.length === 0) {
    console.log(`[DAILY_SUMMARY] No messages in channel ${channelId} to summarize.`);
    return;
  }

  // Filter out bot messages to focus on human activity
  const humanMessages = messages.filter((m: any) => !m.bot_id && m.type === "message").reverse();

  if (humanMessages.length === 0) {
    return;
  }

  const conversationText = humanMessages.map((m: any) => {
    const user = m.user || "Unknown";
    return `${user}: ${m.text}`;
  }).join("\n");

  // 4. Generate Summary
  const prompt = `
Summarize the following Slack conversation from the last 24 hours. 
Highlight key decisions, open questions, and important updates.
Keep it concise and use bullet points.

Conversation:
${conversationText}
`;

  const result = await model.generateContent(prompt);
  const response = result.response;
  const summary = response.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!summary) {
    return;
  }

  // 5. Post Summary
  await axios.post(`${SLACK_API_BASE}/chat.postMessage`, {
    channel: channelId,
    text: "🌅 *Daily Channel Summary*",
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: "🌅 Daily Channel Summary",
          emoji: true
        }
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: summary
        }
      },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: "Generated by Genie AI • " + new Date().toLocaleDateString()
          }
        ]
      }
    ]
  }, {
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json"
    }
  });

  console.log(`[DAILY_SUMMARY] Sent summary to channel ${channelId}`);
}
