import { NextRequest, NextResponse } from "next/server";
import { clerkClient } from "@clerk/nextjs/server";
import { createClient } from "@supabase/supabase-js";
import { jwtVerify } from "jose";
import { CREDITS_PER_DOLLAR, matchPack } from "@/lib/subscription/packs";

const getSupabaseAdmin = () => {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
};

const KOFI_WEBHOOK_SECRET = process.env.KOFI_WEBHOOK_SECRET;

function getJwtSecret(): Uint8Array | null {
  const secret = process.env.KOFI_JWT_SECRET;
  if (!secret) return null;
  return new TextEncoder().encode(secret);
}

interface KofiClaims {
  userId: string;
  email: string;
  plan: string;
}

/**
 * Try to extract and verify a signed JWT from the buyer's `message` field.
 * Returns the claims if the message parses as a valid Lattice Ko-fi JWT,
 * otherwise null (in which case the caller falls back to email matching).
 *
 * The JWT is generated by /api/checkout/kofi/route.ts and pasted by the buyer
 * into the Ko-fi "Add a message" field. Matching by userId is deterministic
 * and immune to email mismatches between Clerk and PayPal.
 */
async function extractJwtClaims(message: unknown): Promise<KofiClaims | null> {
  if (typeof message !== "string" || !message) return null;

  // The buyer may have pasted extra whitespace or notes around the JWT.
  // JWTs are three base64url segments separated by dots; find the first
  // plausible match in the message.
  const match = message.match(/[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/);
  if (!match) return null;

  const secret = getJwtSecret();
  if (!secret) return null;

  try {
    const { payload } = await jwtVerify(match[0], secret, {
      audience: "kofi-checkout",
    });
    if (
      typeof payload.sub === "string" &&
      typeof payload.userId === "string" &&
      typeof payload.email === "string" &&
      typeof payload.plan === "string"
    ) {
      return {
        userId: payload.userId,
        email: payload.email,
        plan: payload.plan,
      };
    }
    return null;
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest) {
  try {
    const supabaseAdmin = getSupabaseAdmin();

    // ── 1. Parse payload ──────────────────────────────────────────
    const formData = await req.formData();
    const rawData = formData.get("data");

    if (!rawData || typeof rawData !== "string") {
      return NextResponse.json({ error: "Invalid payload format" }, { status: 400 });
    }

    const payload = JSON.parse(rawData);

    // ── 2. Verify shared secret ───────────────────────────────────
    // Ko-fi sends a `verification_token` configured in the Ko-fi dashboard.
    // This is NOT a Stripe-grade HMAC — it's a static bearer token. Guard the
    // webhook URL accordingly and rotate if it leaks.
    if (!KOFI_WEBHOOK_SECRET) {
      console.error("Ko-Fi Webhook Error: KOFI_WEBHOOK_SECRET not configured");
      return NextResponse.json({ error: "Webhook not configured" }, { status: 500 });
    }
    if (payload.verification_token !== KOFI_WEBHOOK_SECRET) {
      console.error("Ko-Fi Webhook Error: Invalid verification token");
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const transactionId = payload.kofi_transaction_id;
    const buyerEmail = payload.email;
    const amount = parseFloat(payload.amount);

    if (!transactionId || !amount) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // ── 3. Idempotency: short-circuit if already processed ────────
    const { data: existing } = await supabaseAdmin
      .from("payment_events")
      .select("transaction_id")
      .eq("transaction_id", transactionId)
      .maybeSingle();

    if (existing) {
      console.log(`Webhook ignored: Transaction ${transactionId} already processed.`);
      return NextResponse.json({ status: "Already processed" }, { status: 200 });
    }

    // ── 4. Resolve user: JWT first, email fallback ────────────────
    let clerkUserId: string | null = null;
    let matchedVia: "jwt" | "email" | null = null;

    const jwtClaims = await extractJwtClaims(payload.message);
    if (jwtClaims) {
      clerkUserId = jwtClaims.userId;
      matchedVia = "jwt";
      console.log(
        `[Ko-Fi] JWT match for transaction ${transactionId}: userId=${clerkUserId} plan=${jwtClaims.plan}`
      );
    } else if (buyerEmail) {
      const client = await clerkClient();
      const users = await client.users.getUserList({
        emailAddress: [buyerEmail],
      });
      if (users.data.length > 0) {
        clerkUserId = users.data[0].id;
        matchedVia = "email";
        console.log(
          `[Ko-Fi] Email match for transaction ${transactionId}: userId=${clerkUserId} email=${buyerEmail}`
        );
      }
    }

    if (!clerkUserId) {
      // Payment succeeded but we couldn't resolve a user. Record as unmatched
      // so the manual-claim fallback can pick it up.
      await supabaseAdmin.from("payment_events").insert({
        transaction_id: transactionId,
        email: buyerEmail ?? null,
        amount: payload.amount,
        processed: true,
        matched: false,
      });
      console.error(
        `Paid but unmatched: email=${buyerEmail} tx=${transactionId} (no JWT, no email match)`
      );
      return NextResponse.json({ status: "Unmatched user" }, { status: 200 });
    }

    // ── 5a. Credit the unified ledger ─────────────────────────────
    const creditsToAdd = Math.floor(amount * CREDITS_PER_DOLLAR);
    const pack = matchPack(amount);

    const { error: creditError } = await supabaseAdmin.rpc("increment_credits", {
      p_user_id: clerkUserId,
      p_amount: creditsToAdd,
      p_type: "TOP_UP",
      p_description: `Ko-Fi top-up: $${amount}${pack ? ` (${pack.name})` : ""} (TX ${transactionId})`,
      p_metadata: {
        source: "kofi",
        transaction_id: transactionId,
        amount_usd: amount,
        pack: pack?.id ?? null,
        matched_via: matchedVia,
      },
    });

    if (creditError) {
      console.error(`Ko-Fi Webhook: failed to credit ledger for ${clerkUserId}:`, creditError);
      return NextResponse.json({ error: "Credit update failed" }, { status: 500 });
    }

    // ── 5b. Extend subscription (30-day premium access) ──────────
    const premiumUntil = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

    const { error: subError } = await supabaseAdmin
      .from("subscriptions")
      .upsert(
        {
          clerk_user_id: clerkUserId,
          tier: jwtClaims?.plan ?? "pro",
          premium_until: premiumUntil,
        },
        { onConflict: "clerk_user_id" }
      );

    if (subError) {
      console.error(`Ko-Fi Webhook: failed to extend subscription for ${clerkUserId}:`, subError);
      return NextResponse.json({ error: "Subscription update failed" }, { status: 500 });
    }

    // ── 6. Record idempotency ONLY after both operations succeed ──
    await supabaseAdmin.from("payment_events").insert({
      transaction_id: transactionId,
      email: buyerEmail ?? jwtClaims?.email ?? null,
      amount: payload.amount,
      processed: true,
      matched: true,
    });

    console.log(
      `[Ko-Fi] ${creditsToAdd} credits + premium (30d) granted to ${clerkUserId} via ${matchedVia}`
    );
    return NextResponse.json({
      status: "Success",
      credits: creditsToAdd,
      premium_until: premiumUntil,
      matched_via: matchedVia,
    });
  } catch (error) {
    console.error("Ko-Fi Webhook Processing Error:", error);
    // Return 500 so Ko-Fi retries; nothing recorded yet, idempotency is safe.
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
