-- Migration: 20260826_refinery_jobs_queue
-- Adds a lightweight queue table for the Data Refinery Engine.

create table if not exists public.workspace_refinery_jobs (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null,
  origin_uri text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enforce one pending job per origin_uri per workspace to avoid duplicate ingest.
create unique index if not exists idx_refinery_jobs_pending_unique
  on public.workspace_refinery_jobs (workspace_id, origin_uri)
  where status = 'pending';

create index if not exists idx_refinery_jobs_status
  on public.workspace_refinery_jobs (status, created_at);

-- Keep attempts bounded so failed jobs do not loop forever.
alter table public.workspace_refinery_jobs
  add constraint if not exists refinery_jobs_attempts_check check (attempts >= 0 and attempts <= 10);
