-- Migration: 20260408_bluesky_proactive_posts.sql
-- Log proactive Bluesky posts for dedupe, review, and lane tracking.

CREATE TABLE IF NOT EXISTS bluesky_proactive_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lane TEXT NOT NULL,
  text TEXT NOT NULL,
  topics TEXT[] NOT NULL DEFAULT '{}',
  cta_mode TEXT NOT NULL DEFAULT 'auto',
  grounding TEXT,
  source_kind TEXT,
  post_uri TEXT,
  post_cid TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bluesky_proactive_posts_created_at
  ON bluesky_proactive_posts (created_at DESC);

ALTER TABLE bluesky_proactive_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No public access — bluesky_proactive_posts" ON bluesky_proactive_posts;

CREATE POLICY "No public access — bluesky_proactive_posts"
  ON bluesky_proactive_posts
  FOR ALL
  TO anon, authenticated
  USING (false);

COMMENT ON TABLE bluesky_proactive_posts IS
  'Log of proactive Bluesky posts generated by the Tech Genie planner';
