-- supabase/migrations/20260831001_vectorization_wm_edges.sql
--
-- World-model edge table for the JEPA/MCTS vectorization pipeline.
-- Stores (v_x, action, v_y) tuples generated by the vectorization worker
-- and consumed by MCTS latent-space search.
--
-- Requires pgvector extension (already enabled on Lattice prod DB).

CREATE TABLE IF NOT EXISTS public.wm_edges (
  id          bigserial PRIMARY KEY,
  workspace_id text NOT NULL,
  user_id      text NOT NULL,
  v_x          vector(1024) NOT NULL,
  action       text NOT NULL,
  v_y          vector(1024) NOT NULL,
  embedding_model text NOT NULL DEFAULT 'nvidia/nv-embedqa-e5-v5',
  embedding_dim   int  NOT NULL DEFAULT 1024,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- HNSW index on v_y for sub-millisecond outcome lookup.
-- MCTS will call match_wm_edges() with the predicted next-state embedding.
CREATE INDEX IF NOT EXISTS wm_edges_v_y_hnsw_idx
  ON public.wm_edges
  USING hnsw (v_y vector_cosine_ops)
  WITH (m = 24, ef_construction = 64);

-- Optional index for workspace-scoped queries.
CREATE INDEX IF NOT EXISTS wm_edges_workspace_idx
  ON public.wm_edges (workspace_id);

-- RPC: nearest-neighbor search over wm_edges.
-- Mirrors the existing match_memories() pattern used by vectorStore.ts.
CREATE OR REPLACE FUNCTION match_wm_edges(
  query_embedding   vector(1024),
  match_threshold   float,
  match_count       int,
  filter_workspace  text  DEFAULT NULL,
  filter_user       text  DEFAULT NULL
)
RETURNS TABLE (
  id            bigint,
  workspace_id  text,
  user_id       text,
  v_x           vector(1024),
  action        text,
  v_y           vector(1024),
  similarity    float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    id,
    workspace_id,
    user_id,
    v_x,
    action,
    v_y,
    1 - (v_y <=> query_embedding) as similarity
  FROM public.wm_edges
  WHERE (filter_workspace IS NULL OR workspace_id = filter_workspace)
    AND (filter_user IS NULL OR user_id = filter_user)
    AND 1 - (v_y <=> query_embedding) > match_threshold
  ORDER BY v_y <=> query_embedding
  LIMIT match_count;
$$;
