-- supabase/migrations/20260831001_vectorization_wm_edges.sql
--
-- World-model edge table for the JEPA/MCTS vectorization pipeline.
-- Stores (v_x, action, v_y) tuples generated by the vectorization worker
-- and consumed by MCTS latent-space search.
--
-- Vector dimensions match NIM UniXcoder: 768-dim float4 vectors.

-- 1. Ensure pgvector is available.
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Edge table: v_x/v_y are 768-dim float4 vectors (UniXcoder output).
--    action is stored as jsonb so the MCTS can attach arbitrary payloads
--    (surface tag, branch id, AST hash, compression flags) alongside the
--    semantic label.
CREATE TABLE IF NOT EXISTS public.wm_edges (
  id              bigserial PRIMARY KEY,
  workspace_id    text NOT NULL,
  user_id         text NOT NULL,
  v_x             vector(768) NOT NULL,
  action          jsonb NOT NULL DEFAULT '{}'::jsonb,
  v_y             vector(768) NOT NULL,
  embedding_model text NOT NULL DEFAULT 'nvidia/nv-embedqa-e5-v5',
  embedding_dim   int  NOT NULL DEFAULT 768,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- 3. HNSW indices on BOTH v_x and v_y using cosine distance.
--    v_x index: fast root-state historical lookup.
--    v_y index: fast reward-estimation historical lookup.
CREATE INDEX IF NOT EXISTS wm_edges_v_x_hnsw_idx
  ON public.wm_edges
  USING hnsw (v_x vector_cosine_ops)
  WITH (m = 24, ef_construction = 64);

CREATE INDEX IF NOT EXISTS wm_edges_v_y_hnsw_idx
  ON public.wm_edges
  USING hnsw (v_y vector_cosine_ops)
  WITH (m = 24, ef_construction = 64);

CREATE INDEX IF NOT EXISTS wm_edges_workspace_idx
  ON public.wm_edges (workspace_id);

-- 4. RPC: nearest-neighbor search over wm_edges using cosine distance.
--    Mirrors the existing match_memories() pattern used by vectorStore.ts.
CREATE OR REPLACE FUNCTION match_wm_edges(
  query_vector     vector(768),
  match_threshold  float,
  match_count      int
)
RETURNS TABLE (
  id           bigint,
  workspace_id text,
  user_id      text,
  v_x          vector(768),
  action       jsonb,
  v_y          vector(768),
  similarity   float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    id,
    workspace_id,
    user_id,
    v_x,
    action,
    v_y,
    1 - (v_y <=> query_vector) AS similarity
  FROM public.wm_edges
  WHERE 1 - (v_y <=> query_vector) > match_threshold
  ORDER BY v_y <=> query_vector
  LIMIT match_count;
$$;
