// lib/ucol/projectTemplates.ts
// Scaffold templates for generated projects.
// These ensure generated output is a complete project, not just loose components.
// Required for Phase 2 WebContainers to boot a working app.

export function generatePackageJson(appName: string, techStack: string[]): string {
    const dependencies: Record<string, string> = {
        'react': '^18.2.0',
        'react-dom': '^18.2.0',
        'next': '^14.1.0',
    };

    if (techStack.some(t => /tailwind/i.test(t))) {
        dependencies['tailwindcss'] = '^3.4.0';
        dependencies['autoprefixer'] = '^10.4.0';
        dependencies['postcss'] = '^8.4.0';
    }

    const devDependencies: Record<string, string> = {
        'typescript': '^5.3.0',
        '@types/react': '^18.2.0',
        '@types/react-dom': '^18.2.0',
        '@types/node': '^20.11.0',
    };

    return JSON.stringify({
        name: appName.toLowerCase().replace(/\s+/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            lint: 'next lint',
        },
        dependencies,
        devDependencies,
    }, null, 2);
}

export function generateTsConfig(): string {
    return JSON.stringify({
        compilerOptions: {
            target: 'es5',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: { '@/*': ['./*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
    }, null, 2);
}

export function generateTailwindConfig(): string {
    return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
}

export function generatePostcssConfig(): string {
    return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;
}

export function generateNextConfig(): string {
    return `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
`;
}

export function generateGlobalCss(): string {
    return `@tailwind base;
@tailwind components;
@tailwind utilities;
`;
}

export function generateRootLayout(appName: string): string {
    return `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '${appName}',
  description: 'Generated by Tech Genie Code Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`;
}
